name: onde_gastei_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  args: ^2.4.1
  dotenv: ^4.1.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  jaguar_jwt: ^3.0.0
  logger: ^1.3.0
  mysql1: ^0.20.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  crypto: ^3.0.3

dev_dependencies:
  # lints: ^1.0.0
  test_process: ^2.1.0
  test: ^1.24.3
  shelf_router_generator: ^1.0.4
  build_runner: ^2.4.4
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0
  hard_analyser: ^1.1.0
